### ISSUE TITLE
BETA: /static/ files give 404

### ISSUE THREAD

**Issue by raskas** [inuits/yayata-old#2]
When starting the server with the current configuration the files in /static/ are not found:

```
[03/Jun/2015 09:53:58] "GET /admin/ HTTP/1.1" 200 5756
Not Found: /static/admin/css/base.css
[03/Jun/2015 09:53:58] "GET /static/admin/css/base.css HTTP/1.1" 404 99
```

2 easy workaround are available:
- Set _DEBUG = True_ in beta/settings.py
- Start the server with an extra option: _python manage.py runserver --insecure_

**Comment by VerosK** [comment]
This is normal Django behaviour, `/static/` URIs should be served by dedicated webserver (outside of Django) - see https://docs.djangoproject.com/en/1.8/howto/static-files/#configuring-static-files

One of the `DEBUG` mode features is  serving `/static/` files instead by Django application server. 

This is more yayata documentation issue, than program issue.
